### ISSUE TITLE
OOP: obiekt główny gry

### ISSUE THREAD

**Issue by MacDada** [Glenpl/Sapper#1]
Praktycznie wrapper na to co aktualnie jest.

W `main()` masz jedynie zrobić coś w tym stylu:

```
int main()
{
    Sapper sapper = new Sapper();
    return sapper.run();
}
```

Jak zwykle, na moją składnię cpp nie patrz, chodzi o ideę ;p

Inaczej mówiąc, miej klasę `Sapper` z jedną publiczną metodą `run()`, wszystkie inne jako metody prywatne.

Nie kombinuj za bardzo z jej kształtem – co się da zostaw tak jak jest (np w globalnych zmiennych, stałych, itp). To się zrobi później.

**Comment by jmolinski** [comment]
Zrobione, ale jeszcze kilka poprawek poprawek musi zostać dodane aby to nie było aż tak "kanciaste".

**Comment by MacDada** [comment]
@Glenpl 

`Gameplay` vs `Game` – te dwie zupełnie odrębne role są teraz wymieszane w jednym obiekcie.

Podziel to na zasadzie:
- `Gameplay` reprezentuje „rozgrywkę” – trzyma swojego boarda, stan gry.
- `Game` jako obiekt główny – on ładuje istniejącą rozgrywkę albo tworzy nową.

Inaczej mówiąc `Game` to aplikacja, to coś co jak odpalasz inne gry to masz menu wyboru z ustawieniami, z nową rozgrywką, wczytaniem rozgrywki, zobaczeniem trailera, spisu autorów czy przycisk pomocy ;-)

`Game` (czy `SapperApp` czy samo `Sapper` – jak tam to chcesz nazwać) traktujesz jak obiekt główny. `Gameplay` to tylko konkretna rozgrywka, która może być rozpoczęta nowa, wczytana i przerwana, itp.

`Gameplay` nie powinno „wiedzieć” czy jest nową grą, czy też wczytywaną. Po prostu ma dostać co potrzebuje do działania w konstruktorze od `Gameplay`. A czy `Game` utworzy nowy obiekt `Gameplay` z „czystymi” danymi czy też wczytanymi z pliku, to już dla `Gameplay` zupełnie obojętne.

**Comment by MacDada** [comment]
@Glenpl W sumie to już taki podział Ci się po części zrobił: `Saper` vs `Gameplay`. Choć nazwowo wziąłeś odwrotnie :P

Proponuję nazewnictwo jednak j.w. – bo słowo `gameplay` („rozgrywka”) wyraźnie mówi, że to coś mniej niż cała aplikacja (`gra`, `Sapper`, `Game`, `App`, `SapperApp`).

**Comment by MacDada** [comment]
@Glenpl Ogólnie jak przerzucisz do boarda operacje na polach, to obiekt rozgrywki będzie mógł się skupić na interakcji z użytkownikiem **w trakcie rozgrywki**.
1. Odpalana jest gra
2. Gra inicjalizuje co tam trzeba i gada z użytkownikiem **w kontekście całej gry** (czyli ustawienia językowe, czy wczytaj rozgrywkę czy zrobić nową)
3. Gra przekazuje UI do rozgrywki i rozgrywka przejmuje pałeczkę na czas zabawy.
4. Jak user zdecyduje się wyjść z rozgrywki, to gra z powrotem przejmuje stery (i np zapisuje grę czy pozwala rozpocząć nową czy znów pozwala ustawić język, etc).
