### ISSUE TITLE
OOP: UserInteractor

### ISSUE THREAD

**Issue by MacDada** [Glenpl/Sapper#2]
Po ukończeniu https://github.com/Glenpl/Sapper/issues/1

Utwórz obiekt do komunikacji z użytkownikiem w konsoli.
Inicjalizuj go w konstruktorze `Sapper` i przypisz jako prywatne pole obiektu.

Powinien mieć metody typu `askWhichLanguage()`, które wywołasz w środku `Sapper`.

Inaczej mówiąc, obiekt, który służy do komunikacji z użytkownikiem.

**Comment by MacDada** [comment]
@Glenpl 

`typedef validated_input val_input;` 

Nie rób takich „skrótowców” – mszczą się na czytelności, musiałem zajrzeć do definicji, bo nie wiedziałem o co chodzi (`value_input`?)

---

`validate_input()`

Nie powinno być publiczne – co inne klasy obchodzą jakieś pierdoły robione przez UI? ;-)

---

`set_language()`

`Translator` jest prywatną implementacją, `Saper`a nie interesują takie pierdoły jak język, jakim komunikuje się gracz.

**Comment by MacDada** [comment]
Uspójnij nazewnictwo:
- `play_once_again_question_message()`
- `game_finished_messages()`
- `specify_board_size()`
- `ask_about_prefered_language()`

Metody podobne w zachowaniu, każda używa innych słów kluczowych (`question_message`, `messages`, `specify`, `ask_about`).

**Comment by jmolinski** [comment]
@MacDada poprawione nazewnictwo w klasie UserInteractor: metody zwracające odpowiedź mają teraz w nazwie 'question', a metody wyświetlające tylko jakiś komunikat mają w nazwie 'message', usunąłem funkcję set_language() i zastąpiłem ją specify_UI_language(), usunąłem typedef validated_input

Commit zawierający zmiany:
https://github.com/Glenpl/Sapper/commit/762b8d3ed7cf78e9e901d14cf98a9dd33e2d3108

**Comment by MacDada** [comment]
@Glenpl Bajer: jak wspomnisz w treści commita issue (podasz linka), to GitHub automatycznie podlinkuje tego commita w issue („pingback”).

Przykładowo tutaj w treści commita podałem link do issue:
https://github.com/MacDada/WykopAspieStats/commit/6167e3abb952394941bc350ef9f324674a6e8fdd

Dzięki czemu w issue też się pojawiło info:
https://github.com/MacDada/WykopAspieStats/issues/2

EDIT: zresztą zobacz, że jak tutaj podlinkowałem to issue, to tam też się pojawiło info na ten temat :D
