### ISSUE TITLE
Translator

### ISSUE THREAD

**Issue by MacDada** [Glenpl/Sapper#3]
Obiekt `Translator` powinien mieć metodę tłumaczenia komunikatów.

**Comment by jmolinski** [comment]
Dodane

**Comment by jmolinski** [comment]
Zrobione.

**Comment by jmolinski** [comment]
Trzeba przebudować żeby dało się budować testy

**Comment by MacDada** [comment]
To zamykam na rzecz https://github.com/Glenpl/Sapper/issues/9
