### ISSUE TITLE
BoardPrinter

### ISSUE THREAD

**Issue by MacDada** [Glenpl/Sapper#4]
`BoardPrinter` – propozycja nowego obiektu, który może być wykorzystany przez `UserInteractor` do rysowania po planszy (kilka powiązanych funkcji jest w `UI`).

**Comment by jmolinski** [comment]
@MacDada dodane, powiązany commit:

https://github.com/Glenpl/Sapper/commit/d987ac36a85c6d771a6886c1b291a874d13f96fc

**Comment by MacDada** [comment]
@Glenpl Spox!

W innych komentarzach pisałem o dodatkowych metodach pomocniczych – teraz możesz je dorzucić, a UI nie będzie Ci się przy tym rozrastać.

Do tego pisałem, że masz zahardkodowane „magiczne liczby” – zamiast je hardkodować, możesz utworzyć prywatne pola, które je trzymają („konfiguracja” obiektu) i przekazywać w konstruktorze.

---

Tym samym BoardPrinter będzie elastyczniejszy (dzięki konfiguracji) i może „lepiej się opisywać” (dzięki metodom prywatnym z nazwami). Jednocześnie reszta kodu pozostaje lżejsza :)

**Comment by MacDada** [comment]
I wywal, żeby Board nie był polem – nie ma takiej potrzeby, możesz go wewnętrznie przekazywać przez argumenty.
