### ISSUE TITLE
BoardField – nowy obiekt

### ISSUE THREAD

**Issue by MacDada** [Glenpl/Sapper#5]
1. Co mają stałe typu `FIELD_BOMB` do planszy? Wyraźnie opisują pole planszy, a nie samą planszę.
2. `BoardField` może przechowywać swój stan.

Odnośnie `2.`:
- prywatne pole trzyma info czy jest bombą czy nie
- prywatne pole trzyma info czy jest odkryte czy nie
- `reveal()` sprawia, że jest odkryte (i zwraca info czy jest bombą)
- `mark()`
- `is_marked()`
- `is_hidden()` / `is_visible()`
- wewnętrzna logika nie pozwala np puścić `mark()` czy `reveal()` gdy pole jest już widoczne (rzuca błędem)

**Comment by jmolinski** [comment]
Powiązany commit: https://github.com/Glenpl/Sapper/commit/5c05736e8627e1a4e3eb429ea4247fde20eee1ca
(Zapomniałem podlinkować przy commitowaniu).

Jestem bardzo zadowolony z tej zmiany, uprościła kod - według mnie dużo lepiej teraz wygląda.
